services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data

  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: philosophos
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  neo4j_data:
  pg_data: